streams:
  title:
    mapping:
      from: pipelines/.title/title.blobl
      unarchive: false
    output:
      table: title
      primary: [id, kind]
      columns:
        - name
        - original_name
        - original_language
        - homepage
        - overview
        - tagline
        - popularity
        - release_date
        - softcore
        - status
        - vote_average
        - vote_count
        - poster_path
        - backdrop_path
        - adult
        - version_ts
      updated_at: true

  title_show:
    mapping:
      unarchive: false
    output:
      table: title_show
      primary: [title_id]
      columns:
        - number_of_episodes
        - number_of_seasons
        - last_air_date
        - in_production
        - last_episode_id
        - next_episode_id
        - type
        - version_ts

  alternative_title:
    mapping:
      from: pipelines/.title/alternative_title.blobl
    output:
      table: title_alternative_title
      primary: [title_id, title_kind, iso_3166_1, title]
      columns: [type, version_ts]

  country:
    mapping:
      from: pipelines/.shared/country.blobl
    output:
      table: country
      primary: [iso_3166_1]
      columns: [name]

  title_country:
    mapping:
      from: pipelines/.title/country.blobl
    output:
      table: title_country
      primary: [title_id, title_kind, kind, iso_3166_1]
      columns: [version_ts]

  company:
    mapping:
      from: pipelines/.title/company.blobl
    output:
      table: title_company
      primary: [title_id, title_kind, company_id, company_kind]
      columns: [version_ts]

  facet:
    mapping:
      from: pipelines/.shared/facet.blobl
    output:
      table: facet
      primary: [id, kind]
      columns: [name]
      updated_at: true

  title_facet:
    mapping:
      from: pipelines/.title/facet.blobl
    output:
      table: title_facet
      primary: [title_id, title_kind, facet_id, facet_kind]
      columns: [version_ts]

  language:
    mapping:
      from: pipelines/.shared/language.blobl
    output:
      table: language
      primary: [iso_639_1]
      columns: [name, english_name]

  title_language:
    mapping:
      from: pipelines/.title/language.blobl
    output:
      table: title_language
      primary: [title_id, title_kind, iso_639_1]
      columns: [version_ts]

  translation:
    mapping:
      from: pipelines/.title/translation.blobl
    output:
      table: title_translation
      primary: [title_id, title_kind, iso_3166_1, iso_639_1, field]
      columns: [value, version_ts]

  video:
    mapping:
      from: pipelines/.title/video.blobl
    output:
      table: title_video
      primary: [id]
      columns:
        - key
        - name
        - iso_3166_1
        - iso_639_1
        - official
        - published_at
        - site
        - size
        - type
        - title_id
        - title_kind
        - version_ts

  image:
    mapping:
      from: pipelines/.title/image.blobl
    output:
      table: title_image
      primary: [title_id, title_kind, kind, file_path]
      columns:
        - iso_639_1
        - iso_3166_1
        - width
        - height
        - aspect_ratio
        - vote_average
        - vote_count
        - version_ts

  review:
    mapping:
      from: pipelines/.title/review.blobl
    output:
      table: title_review
      primary: [id]
      columns:
        - author
        - content
        - url
        - created_at
        - updated_at
        - author_avatar_path
        - author_name
        - author_rating
        - author_username
        - title_id
        - title_kind
        - version_ts

  relation:
    mapping:
      from: pipelines/.title/relation.blobl
    output:
      table: title_relation
      primary: [title_id, title_kind, kind, related_id, related_kind]
      columns: [version_ts]

  credit:
    mapping:
      from: pipelines/.title/credit.blobl
    output:
      table: title_credit
      primary: [credit_id]
      columns:
        - person_id
        - kind
        - guest
        - title_id
        - title_kind
        - version_ts

  credit_cast:
    mapping:
      from: pipelines/.title/credit_cast.blobl
    output:
      table: title_credit_cast
      primary: [credit_id]
      columns: [cast_id, order, character, version_ts]

  credit_crew:
    mapping:
      from: pipelines/.title/credit_crew.blobl
    output:
      table: title_credit_crew
      primary: [credit_id]
      columns: [job, department, version_ts]

  created_by:
    output:
      table: title_created_by
      primary: [title_id, person_id]
      columns: [version_ts]

  content_rating:
    output:
      table: title_content_rating
      primary: [title_id, iso_3166_1]
      columns: [rating, descriptors, version_ts]

  episode_group:
    output:
      table: title_episode_group
      primary: [id]
      columns:
        - name
        - description
        - group_count
        - episode_count
        - type
        - company_id
        - title_id
        - version_ts

  screened_theatrically:
    output:
      table: title_screened_theatrically
      primary: [id]
      columns: [season_number, episode_number, title_id, version_ts]

  list:
    mapping:
      from: pipelines/.shared/list.blobl
    output:
      table: list
      primary: [id]
      columns:
        - name
        - description
        - iso_3166_1
        - iso_639_1
        - item_count
        - favorite_count
        - poster_path
        - list_type

  title_list:
    mapping:
      from: pipelines/.title/list.blobl
    output:
      table: title_list
      primary: [list_id, title_id, title_kind]
      columns: [version_ts]
