config:
  kind: production_company
streams:
  company:
    mapping:
      from: pipelines/.company/company.blobl
      unarchive: false
    output:
      table: company
      primary: [id, kind]
      columns:
        - name
        - description
        - headquarters
        - homepage
        - logo_path
        - origin_country
        - parent_company
      updated_at: true
