streams:
  person:
    mapping:
      unarchive: false
    output:
      table: person
      primary: [id]
      columns:
        - name
        - biography
        - birthday
        - deathday
        - gender
        - homepage
        - imdb_id
        - known_for_department
        - place_of_birth
        - popularity
        - profile_path
        - adult
        - version_ts
      updated_at: true

  aka:
    output:
      table: person_aka
      primary: [person_id, also_known_as]
      columns: [version_ts]

  image:
    output:
      table: person_image
      primary: [person_id, kind, file_path]
      columns:
        - width
        - height
        - aspect_ratio
        - vote_average
        - vote_count
        - version_ts

  translation:
    output:
      table: person_translation
      primary: [person_id, iso_3166_1, iso_639_1, field]
      columns: [value, primary, version_ts]
