scrape_configs:
  - job_name: redpanda
    static_configs:
      - targets: [kafka.lokal:9644]
    metrics_path: /public_metrics
    scrape_interval: 5s

  - job_name: redpanda_internal
    static_configs:
      - targets: [kafka.lokal:9644]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter.lokal:9187"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: pgbouncer
    static_configs:
      - targets: ["pgbouncer-exporter.lokal:9127"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: vector
    static_configs:
      - targets: ["vector.lokal:9598"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: tei
    static_configs:
      - targets: ["tei.lokal:8080"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: seed
    static_configs:
      - targets: ["seed.lokal:9598"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: enrich
    static_configs:
      - targets: ["enrich.lokal:4195"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: normalize
    static_configs:
      - targets: ["normalize.lokal:4195"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: embed
    static_configs:
      - targets: ["embed.lokal:4195"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: ingest
    static_configs:
      - targets: ["ingest.lokal:4195"]
    metrics_path: /metrics
    scrape_interval: 5s
