x-healthcheck: &healthcheck
  interval: 30s
  timeout: 5s
  retries: 15
  start_period: 3s
  start_interval: 1s

x-pipeline: &pipeline
  build:
    context: ${PWD}/services/pipeline
    args:
      ALPINE_IMAGE: ${ALPINE_IMAGE:?}
      CUE_IMAGE: ${CUE_IMAGE:?}
      RD_CONNECT_IMAGE: ${RD_CONNECT_IMAGE:?}
      REDPANDA_IMAGE: ${REDPANDA_IMAGE:?}
      VECTOR_IMAGE: ${VECTOR_IMAGE:?}
  entrypoint: /bin/bash
  command: /app/entrypoint.sh
  user: root
  volumes:
    - ${PWD}/services/pipeline/app:/app:ro
  
  tmpfs:
    - /config
    - /home/pipeline

x-common-env: &common-env
  KAFKA_BROKERS: ${KAFKA_BROKERS:?}

x-vector-env: &vector-env
  <<: *common-env
  EXEC_CMD: vector -w -c "$$CONFIGDIR_TARGET/vector/*.yaml" -c "$$CONFIGDIR_TARGET/$$SERVICE_NAME/**/*.yaml"

x-connect-env: &connect-env
  <<: *common-env
  EXEC_CMD: redpanda-connect streams -o $$CONFIGDIR_TARGET/connect/observability.yaml -r $$CONFIGDIR_TARGET/connect/resources.yaml -w $$CONFIGDIR_TARGET/$$SERVICE_NAME/**/*.yaml

volumes:
  seed_tmdb:
  seed_vector:

networks:
  net-pipeline:

services:
  kafka-init:
    <<: *pipeline
    restart: on-failure
    environment:
      <<: *common-env
      EXEC_CMD: /app/kafka/entrypoint.sh
      KAFKA_CLEANUP_POLICY: ${KAFKA_CLEANUP_POLICY:?}
      KAFKA_COMPRESSION_TYPE: ${KAFKA_COMPRESSION_TYPE:?}
      KAFKA_MAX_MESSAGE_BYTES: ${KAFKA_MAX_MESSAGE_BYTES:?}
      KAFKA_NUM_PARTITIONS: ${KAFKA_NUM_PARTITIONS:?}
    networks:
      net-kafka:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 64M
    depends_on:
      redpanda: { condition: service_healthy }
    labels:
      # Enable collecting logs
      - "tmdb.log.enable=true"

  seed:
    <<: *pipeline
    restart: unless-stopped
    environment:
      <<: *vector-env
      SERVICE_NAME: seed
      DATADIR_TMDB: ${DATADIR_TMDB:?}
      DATADIR_VECTOR: ${DATADIR_VECTOR:?}
      TMDB_FILES_API_URL: http://tmdb.lokal:9090
      TMDB_DOWNLOAD_INTERVAL_SECS: 3600
    volumes:
      - seed_tmdb:${DATADIR_TMDB:?}
      - seed_vector:${DATADIR_VECTOR:?}
      - ${PWD}/services/pipeline/app:/app:ro
    networks:
      net-kafka:
      net-pipeline: { aliases: [seed.lokal] }
      net-tmdb:
    depends_on:
      kafka-init: { condition: service_completed_successfully }
      redpanda: { condition: service_healthy }
      tmdb: { condition: service_healthy }
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
    labels:
      # Enable collecting logs
      - "tmdb.log.enable=true"
    healthcheck:
      <<: *healthcheck
      test: [CMD, wget, -q, --spider, http://0.0.0.0:8686/health]

  enrich:
    <<: *pipeline
    restart: unless-stopped
    environment:
      <<: *connect-env
      SERVICE_NAME: enrich
      TMDB_API_URL: http://tmdb.lokal:8080
      TMDB_API_SECRET: ${TMDB_API_SECRET:?}
    networks:
      net-kafka:
      net-pipeline: { aliases: [enrich.lokal] }
      net-tmdb:
    depends_on:
      kafka-init: { condition: service_completed_successfully }
      redpanda: { condition: service_healthy }
      tmdb: { condition: service_healthy }
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    labels:
      # Enable collecting logs
      - "tmdb.log.enable=true"
    healthcheck:
      <<: *healthcheck
      test: [CMD, wget, -q, --spider, http://0.0.0.0:4195/ready]

  normalize:
    <<: *pipeline
    restart: unless-stopped
    environment:
      <<: *connect-env
      SERVICE_NAME: normalize
    networks:
      net-kafka:
      net-pipeline: { aliases: [normalize.lokal] }
    depends_on:
      kafka-init: { condition: service_completed_successfully }
      redpanda: { condition: service_healthy }
    deploy:
      resources:
        limits:
          cpus: "${NORMALIZE_RESOURCE_CPU:?}"
          memory: ${NORMALIZE_RESOURCE_MEM:?}
    labels:
      # Enable collecting logs
      - "tmdb.log.enable=true"
    healthcheck:
      <<: *healthcheck
      test: [CMD, wget, -q, --spider, http://0.0.0.0:4195/ready]

  embed:
    <<: *pipeline
    restart: unless-stopped
    environment:
      <<: *connect-env
      SERVICE_NAME: embed
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:?}
      EMBEDDING_DIMENSIONS: ${EMBEDDING_DIMENSIONS:?}
    networks:
      net-kafka:
      net-pipeline: { aliases: [embed.lokal] }
      net-tei:
    depends_on:
      kafka-init: { condition: service_completed_successfully }
      tei: { condition: service_healthy }
      redpanda: { condition: service_healthy }
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    labels:
      # Enable collecting logs
      - "tmdb.log.enable=true"
    healthcheck:
      <<: *healthcheck
      test: [CMD, wget, -q, --spider, http://0.0.0.0:4195/ready]
    profiles:
      - embed

  ingest:
    <<: *pipeline
    restart: unless-stopped
    environment:
      <<: *connect-env
      SERVICE_NAME: ingest
      PG_SCHEMA: ${PG_SCHEMA:?}
      POSTGRES_URL: ${POSTGRES_URL:?}
      INGEST_MAX_IN_FLIGHT: ${INGEST_MAX_IN_FLIGHT:?}
      INGEST_CONN_MAX_OPEN: ${INGEST_CONN_MAX_OPEN:?}
      INGEST_CONN_MAX_IDLE: ${INGEST_CONN_MAX_IDLE:?}
      INGEST_CONN_MAX_LIFE_TIME: ${INGEST_CONN_MAX_LIFE_TIME:?}
      EMBEDDING_DIMENSIONS_MAX: ${EMBEDDING_DIMENSIONS_MAX:?}
    networks:
      net-kafka:
      net-pgbouncer:
      net-pipeline: { aliases: [ingest.lokal] }
    depends_on:
      kafka-init: { condition: service_completed_successfully }
      migrate: { condition: service_completed_successfully }
      pgbouncer: { condition: service_healthy }
      redpanda: { condition: service_healthy }
    deploy:
      resources:
        limits:
          cpus: "${INGEST_RESOURCE_CPU:?}"
          memory: ${INGEST_RESOURCE_MEM:?}
    labels:
      # Enable collecting logs
      - "tmdb.log.enable=true"
    healthcheck:
      <<: *healthcheck
      test: [CMD, wget, -q, --spider, http://0.0.0.0:4195/ready]
