streams:
  collection:
    mapping:
      unarchive: false
    output:
      table: collection
      primary: [id]
      columns:
        - id
        - name
        - overview
        - poster_path
        - backdrop_path
        - original_name
        - original_language
        - version_ts
      updated_at: true

  collection_part:
    mapping:
      unarchive: true
    output:
      table: collection_part
      primary: [collection_id, part_id]
      columns: [part_index, media_type, version_ts]
